/**
 * 
 * This file was automatically generated by the Repast Simphony Agent Editor.
 * Please see http://repast.sourceforge.net/ for details.
 * 
 */

/**
 *
 * Set the package name.
 *
 */
package Sudden_Stop;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import cern.jet.random.*;
import repast.simphony.context.Context;
import repast.simphony.engine.environment.*;
import repast.simphony.engine.schedule.*;
import repast.simphony.parameter.*;
import repast.simphony.random.*;
import repast.simphony.util.collections.IndexedIterable;
import static java.lang.Math.*;
import static repast.simphony.essentials.RepastEssentials.*;

public class SupplyManager {

	public static final String TEXT_DELIM = "\"";
	public static final String FIELD_SEPARATOR = ",";
	public static final String FILE_NAME = "C:\\Users\\jgsanchez\\Documents\\Local Workspace\\Sudden Stop\\output\\All Parameters.txt";
	public static final String NEW_LINE = "\r\n";

	private Context<Object> context;

	public SupplyManager(Context<Object> context) {

		this.context = context;
		context.add(this);

		price = (Double) GetParameter("priceOfSubstitute");

		rDEfficiencyNormal = RandomHelper.createNormal(
				(Double) GetParameter("rDEfficiencyMean"),
				(Double) GetParameter("rDEfficiencyStdDev")
						* (Double) GetParameter("rDEfficiencyMean"));
		iniKNormal = RandomHelper.createNormal(
				(Double) GetParameter("iniKMean"),
				(Double) GetParameter("iniKStdDev")
						* (Double) GetParameter("iniKMean"));
		entrantsNormal = RandomHelper.createNormal(
				(Double) GetParameter("entrantsMean"),
				(Double) GetParameter("entrantsStdDev")
						* (Double) GetParameter("entrantsMean"));
		innovationErrorNormal = RandomHelper.createNormal(1.0,
				(Double) GetParameter("innovationErrorStdDev"));
		firstUnitCostNormal = RandomHelper.createNormal(
				(Double) GetParameter("firstUnitCostMean"),
				(Double) GetParameter("firstUnitCostStdDev")
						* (Double) GetParameter("firstUnitCostMean"));

		/*
		 * If the learning rate variance is too big for the mean, it is set to
		 * the minimum value
		 */
		double lRMean = (Double) GetParameter("learningRateMean");

		double lRVar = pow(
				(Double) GetParameter("learningRateStdDev") * lRMean, 2.0);

		if (lRVar >= (lRMean - 0.5) * (1 - lRMean)) {
			lRVar = (lRMean - 0.5) * (1 - lRMean) - 0.000001;
		}

		double alfa = 2 / lRVar * (lRMean - 0.5)
				* ((lRMean - 0.5) * (1 - lRMean) - lRVar);
		double beta = 2 / lRVar * (1 - lRMean)
				* ((lRMean - 0.5) * (1 - lRMean) - lRVar);
		learningRateDistrib = RandomHelper.createBeta(alfa, beta);

		Firm.supplyManager = this;

	}

	private void entry(int potentialEntrants) {

		// Check different types of Entry
		Firm tmpFirm;
		double tmpPerformance;
		bornFirms = 0;

		// This is a loop.
		for (int j = 1; j <= potentialEntrants; j++) {

			// Destroy if not profitable
			tmpFirm = new Firm(context);

			tmpPerformance = (Double) GetParameter("performanceWeight")
					* (Double) GetParameter("initialPerformance")
					+ (1 - (Double) GetParameter("performanceWeight"))
					* tmpFirm.profit(tmpFirm.currentState,
							tmpFirm.nextDecision, price)
					/ tmpFirm.currentState.capital;
			if (tmpPerformance <= (Double) GetParameter("minimumPerformance")) {
				RemoveAgentFromModel(tmpFirm);
			} else {
				bornFirms++;
			}

		}

	}

	private void processOffers() {

		IndexedIterable<Object> firms = context.getObjects(Firm.class);

		totalFirms = firms.size();

		if (totalFirms == 0.0) {
			totalQuantity = 0.0;
		} else {
			double tmpQ = 0.0;
			for (Object f : firms) {
				tmpQ += ((Firm) f).offer();
			}
			totalQuantity = tmpQ;
		}

		price = Demand.price(totalQuantity);

		List<Firm> toKill = new ArrayList<Firm>(firms.size());

		for (Object f : context.getObjects(Firm.class)) {

			// Process Demand Response
			if (!((Firm) f).processDemandResponse()) {
				toKill.add((Firm) f);
			}

		}

		dead = toKill.size();
		for (Firm f : toKill) {
			RemoveAgentFromModel(f);
		}

		firms = context.getObjects(Firm.class);
		totalFBeforeExit = totalFirms;
		totalFirms = firms.size();
		totalQBeforeExit = totalQuantity;

		if (totalFirms == 0.0) {
			totalQuantity = 0.0;
		} else {
			double tmpQ = 0.0;
			for (Object f : firms) {
				tmpQ += ((Firm) f).currentDecision.quantity;
			}
			totalQuantity = tmpQ;
		}

	}

	@ScheduledMethod(start = 1d, pick = 9223372036854775807l, interval = 1d, shuffle = true)
	public void step() {

		// Manage Entry
		double potentialEntrants = entrantsNormal.nextDouble();
		if (potentialEntrants > 0)
			entry((int) round(potentialEntrants));

		processOffers();

		// Planning
		IndexedIterable<Object> firms = context.getObjects(Firm.class);
		for (Object f : firms)
			((Firm) f).plan();

	}

	@ScheduledMethod(start = 1, interval = 1, shuffle = true)
	public void saveParams() {

		if (RunEnvironment.getInstance().isBatch()) {

			FileWriter paramsFile;
			try {
				paramsFile = new FileWriter(FILE_NAME, true);

				Parameters params = RunEnvironment.getInstance()
						.getParameters();

				Schema schema = params.getSchema();
				for (String paramName : schema.parameterNames()) {
					// write run number
					paramsFile.write(((Integer) RunState.getInstance()
							.getRunInfo().getRunNumber()).toString());

					// write param Name
					paramsFile.write(FIELD_SEPARATOR + TEXT_DELIM + paramName
							+ TEXT_DELIM);

					// writes param value
					paramsFile.write(FIELD_SEPARATOR + GetParameter(paramName));

					// new line
					paramsFile.write(NEW_LINE);
				}

				paramsFile.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}

	}

	public String toString() {

		return "SupplyManager";

	}

	@Parameter(displayName = "Total Quantity", usageName = "totalQuantity")
	public double getTotalQuantity() {
		return totalQuantity;
	}

	public double totalQuantity = 0;

	@Parameter(displayName = "Price", usageName = "price")
	public double getPrice() {
		return price;
	}

	public double price = 0;

	/**
	 * 
	 * This is an agent property.
	 * 
	 * @field dead
	 * 
	 */
	@Parameter(displayName = "Dead", usageName = "dead")
	public double getDead() {
		return dead;
	}

	public double dead = 0;

	/**
	 * 
	 * This is an agent property.
	 * 
	 * @field bornFirms
	 * 
	 */
	@Parameter(displayName = "Born Firms", usageName = "bornFirms")
	public int getBornFirms() {
		return bornFirms;
	}

	public int bornFirms = 0;

	/**
	 * 
	 * This is an agent property.
	 * 
	 * @field totalFirms
	 * 
	 */
	@Parameter(displayName = "Total Firms", usageName = "totalFirms")
	public double getTotalFirms() {
		return totalFirms;
	}

	public double totalFirms = 1.0;

	/**
	 * 
	 * This is an agent property.
	 * 
	 * @field totalQBeforeExit
	 * 
	 */
	@Parameter(displayName = "Total Q Before Exit", usageName = "totalQBeforeExit")
	public double getTotalQBeforeExit() {
		return totalQBeforeExit;
	}

	public double totalQBeforeExit = 0;

	/**
	 * 
	 * This is an agent property.
	 * 
	 * @field totalFBeforeExit
	 * 
	 */
	@Parameter(displayName = "Total F Before Exit", usageName = "totalFBeforeExit")
	public double getTotalFBeforeExit() {
		return totalFBeforeExit;
	}

	public double totalFBeforeExit = 1.0;

	public Normal iniKNormal = null;

	public Beta learningRateDistrib = null;

	public Normal entrantsNormal = null;

	public Normal rDEfficiencyNormal = null;

	public Normal innovationErrorNormal = null;

	public Normal firstUnitCostNormal = null;

}
